spring:
  application:
    name: reactiveAuthService
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/authservice
    username: postgres
    password: 786@admin
  flyway:
    url: jdbc:postgresql://localhost:5432/authservice
    user: postgres
    password: 786@admin
  devtools:
    restart:
      enabled: true 
    livereload:
      enabled: true
